---
roles_to_exclude:
  # I'm not using Windows anymore (I had enough)
  - vscode
  - powershell
  - windows_setup
  - glazewm

  # I'm not using X anymore
  - i3
  - i3status
  - polybar
  - rofi
  - awesome

  # Foot is my choice now
  - alacritty
  - wezterm

  # Vanilla things I played with for fun
  - emacs
  - neovim

  # I'm afraid of it
  - doom

  # Not now
  - ssh
  - git
  - wakatime
  - vifm  # lf better
  - fcitx # I'm not chinese



default_roles:
  - powershell
  - gtk3
  - i3status
  - doom
  - virtual
  - tmux
  - ssh
  - sway
  - swaylock
  - lazy_neovim
  - xplr
  - ideavim
  - alacritty
  - vscode
  - polybar
  - rofi
  - glazewm
  - vifm
  - mise
  - lazygit
  - i3
  - docker
  - windows_setup
  - wezterm
  - neovim
  - waybar
  - fuzzel
  - hiddify
  - firefox
  - oh-my-posh
  - foot
  - awesome
  - emacs
  - linux_setup
  - programs
  - wakatime
  - mako
  - fcitx
  - bash
  - lf
  - git
