- name: Create local bin directory
  file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    mode: '0755'
  when: ansible_os_family == 'Linux'

- name: Install Oh My Posh on Linux
  shell: >
    curl -s https://ohmyposh.dev/install.sh | bash -s -- -d {{ ansible_user_dir }}/.local/bin
  args:
    creates: "{{ ansible_user_dir }}/.local/bin/oh-my-posh"
  when: ansible_os_family == 'Linux'

- name: "{{ role_name }} | Install oh-my-posh on Windows"
  community.windows.scoop:
    name: oh-my-posh
    state: present
  when: ansible_os_family == 'Windows'

- name: Set OS-specific config paths
  set_fact:
    config_path: "{{ ansible_user_dir }}/.config/oh-my-posh"

- name: Include common copy tasks
  include_tasks: roles/common_tasks/tasks/copy_configs.yml